# Generated by Django 4.1.4 on 2022-12-09 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='breed',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='mor_image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Tommy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='owner_name',
            field=models.CharField(default='Shimon', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='owner_number',
            field=models.IntegerField(default='03207051998', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sec_image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
